# Generated by Django 5.1.1 on 2024-09-19 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_worker_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='tasks.position'),
            preserve_default=False,
        ),
    ]
