# Generated by Django 4.2.16 on 2024-09-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_givers_task_giver'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='avatar',
            field=models.CharField(default='avatars/avatar1.png', max_length=100),
        ),
    ]
